# Generated by Django 4.1.3 on 2022-12-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_obra_trabajadores_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
        migrations.RemoveField(
            model_name='trabajadores',
            name='user',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
