# Generated by Django 4.1.3 on 2022-12-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_empresa_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
