# Generated by Django 4.1.3 on 2022-12-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trabajadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
