# Generated by Django 4.1.3 on 2022-12-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_trabajadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
