# Generated by Django 4.1.3 on 2022-12-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_trabajadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajadores',
        ),
    ]
